# Start: sudo docker compose up -d --build
# Logs: docker compose logs --follow --tail 1000
# Stop: sudo docker compose down --remove-orphans
# Update: sudo docker compose pull
# Restart: sudo docker compose restart
# UI: http://192.168.1.3:9000
services:
  go-rtsp-to-jsmpeg:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 9000:9000
    volumes:
      - ./config:/app/config
      - ./public:/app/public
    restart: unless-stopped
