# Start: docker compose up -d --build
# Logs: docker compose logs --follow --tail 1000
# Stop: docker compose down

services:
  go-ffmpeg-to-jsmpeg:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 9000:9000
    volumes:
      - ./config:/app/config
      - ./public:/app/public
    restart: unless-stopped
